default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  encoding: unicode

development:
  <<: *default
  database: blog
  username: postgres
  password: 123456
  host: 127.0.0.1

test:
  <<: *default
  database: blog

production:
  <<: *default
  pool: 5
  database: <%= ENV['BASE_DE_DATOS'] %>
  username: <%= ENV['DB_USUARIO'] %>
  password: <%= ENV['DB_CLAVE'] %>
