default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  encoding: utf8
  username: postgres
  password: 123456
  host: 127.0.0.1

development:
  <<: *default
  database: blog

test:
  <<: *default
  database: blog

production:
  <<: *default
  database: blog
